In [ ]:
# ⚽️ Football Forward Efficiency Analysis
**[Task 1-4: Setup, Goals & Data Questions]**

**EN:** This project aims to analyze the finishing efficiency of top football forwards by comparing their actual Goals scored against their Expected Goals (xG). The goal is to identify which players overperform their underlying metrics.
**TH:** โปรเจกต์นี้มีเป้าหมายเพื่อวิเคราะห์ความเฉียบคมในการทำประตูของกองหน้าระดับท็อป โดยเปรียบเทียบระหว่าง "ประตูที่ทำได้จริง (Goals)" กับ "โอกาสความน่าจะเป็นในการได้ประตู (xG)" เพื่อค้นหาว่าผู้เล่นคนใดมีประสิทธิภาพการจบสกอร์สูงกว่าค่ามาตรฐาน

In [1]:
# [Task 5: Load and Inspect the Data]

import pandas as pd

# EN: Create a dataset for top forwards (Goals vs xG)
# TH: สร้างชุดข้อมูลสถิติของกองหน้าระดับท็อป (ประตูจริง เปรียบเทียบกับ xG)
data = {
    'Player': ['Mohamed Salah', 'Erling Haaland', 'Bukayo Saka', 'Son Heung-min'],
    'Team': ['Liverpool', 'Man City', 'Arsenal', 'Spurs'],
    'Goals': [18, 25, 14, 15],
    'xG': [16.5, 26.2, 11.8, 12.1]
}

# EN: Convert into a Pandas DataFrame
# TH: แปลงข้อมูลให้เป็นตาราง Pandas DataFrame
df = pd.DataFrame(data)

# EN: Inspect the first few rows and data information
# TH: ตรวจสอบข้อมูล 5 แถวแรก และดูรายละเอียดของชุดข้อมูล
print("--- Data Preview / ตัวอย่างข้อมูล ---")
display(df.head())

print("\n--- Data Info / โครงสร้างข้อมูล ---")
df.info()

--- Data Preview / ตัวอย่างข้อมูล ---

           Player       Team  Goals    xG
0   Mohamed Salah  Liverpool     18  16.5
1  Erling Haaland   Man City     25  26.2
2     Bukayo Saka    Arsenal     14  11.8
3   Son Heung-min      Spurs     15  12.1

--- Data Info / โครงสร้างข้อมูล ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  4 non-null      object
 1   Team    4 non-null      object
 2   Goals   4 non-null      int64
 3   xG      4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [2]:
# [Task 6: Data Cleaning]

# EN: Fill missing values with 0 and ensure numeric data types
# TH: เติมค่าว่าง (ถ้ามี) ด้วย 0 และตรวจสอบให้แน่ใจว่าข้อมูลเป็นตัวเลขสำหรับการคำนวณ
df['Goals'] = df['Goals'].fillna(0)
df['xG'] = df['xG'].fillna(0)

df['Goals'] = pd.to_numeric(df['Goals'])
df['xG'] = pd.to_numeric(df['xG'])

# EN: Verify that there are no missing values left
# TH: ยืนยันผลการทำความสะอาดข้อมูลว่าไม่มีค่าว่างหลงเหลืออยู่
print("--- Missing Values Check / ตรวจสอบค่าว่าง ---")
print(df[['Goals', 'xG']].isnull().sum())

--- Missing Values Check / ตรวจสอบค่าว่าง ---
Goals    0
xG       0
dtype: int64

In [3]:
# [Task 7: Data Preparation]

# EN: Calculate finishing efficiency (Goals - xG). Positive values indicate overperformance.
# TH: สร้างคอลัมน์คำนวณความเฉียบคม (Goals - xG) ค่าบวกหมายถึงการยิงประตูได้ดีกว่าโอกาสที่ควรจะเป็น
df['Finishing_Efficiency'] = df['Goals'] - df['xG']

# EN: Preview the updated DataFrame
# TH: แสดงผลตารางที่เพิ่มคอลัมน์ใหม่แล้ว
display(df[['Player', 'Goals', 'xG', 'Finishing_Efficiency']].head())

           Player  Goals    xG  Finishing_Efficiency
0   Mohamed Salah     18  16.5                   1.5
1  Erling Haaland     25  26.2                  -1.2
2     Bukayo Saka     14  11.8                   2.2
3   Son Heung-min     15  12.1                   2.9

In [4]:
# [Task 8: Exploratory Data Analysis (EDA)]

# EN: Sort players by Finishing Efficiency in descending order to find the most clinical forward
# TH: จัดเรียงลำดับผู้เล่นตามความเฉียบคมจากมากไปน้อย เพื่อหากองหน้าที่จบสกอร์ได้ดีที่สุด
df_sorted = df.sort_values(by='Finishing_Efficiency', ascending=False)

print("🏆 Top Forwards by Finishing Efficiency / จัดอันดับกองหน้าที่เฉียบคมที่สุด 🏆")
display(df_sorted)

🏆 Top Forwards by Finishing Efficiency / จัดอันดับกองหน้าที่เฉียบคมที่สุด 🏆

           Player       Team  Goals    xG  Finishing_Efficiency
3   Son Heung-min      Spurs     15  12.1                   2.9
2     Bukayo Saka    Arsenal     14  11.8                   2.2
0   Mohamed Salah  Liverpool     18  16.5                   1.5
1  Erling Haaland   Man City     25  26.2                  -1.2

In [ ]:
## 🏆 Executive Summary & Conclusions / บทสรุปผลการวิเคราะห์ 
**[Task 9: Conclusions]**

**🇬🇧 English Version:**
Based on the statistical analysis comparing actual goal output against Expected Goals (xG) metrics, the key findings are:
* **Top Finishing Efficiency:** Son Heung-min demonstrates the highest clinical efficiency, overperforming his expected metrics by +2.9 goals.
* **Mohamed Salah (Liverpool):** Consistently maintains elite-level performance, converting chances above the statistical baseline (+1.5 goals over xG).
* **Erling Haaland:** Despite leading the scoring charts with 25 goals, he exhibits a slight underperformance relative to his xG (-1.2), indicating a massive volume of high-value chances generated by his team.

**🇹🇭 Thai Version:**
จากการวิเคราะห์เชิงสถิติเพื่อเปรียบเทียบประสิทธิภาพการทำประตูจริง (Goals) กับค่าความน่าจะเป็นในการได้ประตู (xG) มีข้อสรุปที่สำคัญดังนี้:
* **ผู้เล่นที่มีประสิทธิภาพการจบสกอร์สูงสุด:** ซน ฮึง-มิน แสดงให้เห็นถึงความเฉียบคมในการพังประตูสูงสุด โดยผลงานจริงดีกว่าค่าคาดการณ์ (Overperformance) ถึง +2.9 ประตู
* **โมฮาเหม็ด ซาลาห์ (Liverpool):** รักษามาตรฐานการเล่นในระดับสูงอย่างสม่ำเสมอ โดยทำประตูได้สูงกว่าค่ามาตรฐาน xG (+1.5 ประตู)
* **เออร์ลิง ฮาลันด์:** แม้จะเป็นดาวซัลโวสูงสุด (25 ประตู) แต่มีสถิติความเฉียบคมติดลบเล็กน้อย (-1.2) ซึ่งชี้ให้เห็นว่าระบบทีมสามารถสร้างโอกาสทองให้เขาได้จำนวนมหาศาล